src/Entity/Sites.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SitesRepository")
 */
class Sites
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Length(
     * min = 5,
     * max = 40
     * )
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="date")
     */
    private $publishedAt;

    /**
     * @ORM\Column(type="string")
     */
    private $illustration;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="sites")
     * * @Assert\NotBlank
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * * @Assert\NotBlank
     * * @Assert\Url
     */
    private $link;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getIllustration()
    {
        return $this->illustration;
    }

    public function setIllustration($illustration)
    {
        $this->illustration = $illustration;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(?string $link): self
    {
        $this->link = $link;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_WRITER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }
    /**
     * @Assert\NotBlank(groups={"registration"})
     * @Assert\Length(max=4096)
     */
    private $plainPassword;

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setPlainPassword($password)
    {
        $this->plainPassword = $password;
    }
    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Form/SitesType.php
<?php

namespace App\Form;

use App\Entity\Sites;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class SitesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, ['label' => 'Nom de l\'outil :', 'help' => '40 caractères max.'])
            ->add('description', TextareaType::class, ['label' => 'Description de l\'outil :'])
            // ->add('publishedAt')
            ->add('illustration', FileType::class, [

                'label' => 'Illustration :',
                'label_attr' => ['data-browse' => 'parcourir ...'],
                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '5024k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'S\'il vous plaît mettez une image valide',
                    ])
                ],
            ])
            ->add('link', TextType::class, ['label' => 'Lien de l\'outil :'])

            ->add('category', null, [
                'label' => 'Mots clés :',
                'required' => false,
                'multiple' => false,
                'expanded' => true,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Sites::class,
        ]);
    }
}

src/Controller/SitesController.php
<?php

namespace App\Controller;

use App\Entity\Sites;
use App\Form\SitesType;
use App\Repository\SitesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use App\Entity\Category;
use Doctrine\ORM\EntityManagerInterface;

/**
 * @Route("admin")
 */
class SitesController extends AbstractController
{
    /**
     * @Route("/", name="sites_index", methods={"GET"})
     */
    public function index(SitesRepository $sitesRepository, EntityManagerInterface $em)
    {
        return $this->render('backoffice/sites/index.html.twig', [
            'sites' => $sitesRepository->findAll(),

            'categories' => $em->getRepository(Category::class)->findAll(),
        ]);
    }
    /**
     * @Route("admin/latest", name="sites_index_latest", methods={"GET"})
     */
    public function index_latest(SitesRepository $sitesRepository, EntityManagerInterface $em)
    {
        return $this->render('backoffice/sites/index2.html.twig', [
            'sites' => $sitesRepository->findAll(),
            'categories' => $em->getRepository(Category::class)->findAll(),
        ]);
    }
    /**
     * @Route("/new", name="sites_new", methods={"GET","POST"})
     */
    public function new(Request $request, EntityManagerInterface $em)
    {
        $site = new Sites();
        $site->setPublishedAt(new \DateTime());
        $form = $this->createForm(SitesType::class, $site);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $illustration = $form->get('illustration')->getData();
            if ($illustration) {
                $originalFilename = pathinfo($illustration->getClientOriginalName(), PATHINFO_FILENAME);
                //$safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $originalFilename . '-' . uniqid() . '.' . $illustration->guessExtension();
                try {
                    $illustration->move(
                        $this->getParameter('illustration_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                }
                $site->setIllustration($newFilename);
            }

            $entityManager =  $this->getDoctrine()->getManager();
            $entityManager->persist($site);
            $entityManager->flush();

            return $this->redirectToRoute('sites_index');
        }

        return $this->render('backoffice/sites/new.html.twig', [

            'form' => $form->createView(),
            'categories' => $em->getRepository(Category::class)->findAll(),
        ]);
    }



    /**
     * @Route("/{id}/edit", name="sites_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Sites $site,  EntityManagerInterface $em)
    {
        $site->setPublishedAt(new \DateTime());
        $form = $this->createForm(SitesType::class, $site);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $illustration = $form->get('illustration')->getData();
            if ($illustration) {
                $originalFilename = pathinfo($illustration->getClientOriginalName(), PATHINFO_FILENAME);
                //$safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $originalFilename . '-' . uniqid() . '.' . $illustration->guessExtension();
                try {
                    $illustration->move(
                        $this->getParameter('illustration_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                }
                $site->setIllustration($newFilename);
            }
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('sites_index');
        }

        return $this->render('backoffice/sites/edit.html.twig', [
            'site' => $site,
            'form' => $form->createView(),
            'categories' => $em->getRepository(Category::class)->findAll(),
        ]);
    }

    /**
     * @Route("/{id}", name="sites_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Sites $site): Response
    {
        if ($this->isCsrfTokenValid('delete' . $site->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($site);
            $entityManager->flush();
        }

        return $this->redirectToRoute('sites_index');
    }

    /**
     * @Route("/{id}/ordre", name="sites_tag_show", methods={"GET"}, requirements={"id":"\d+"})
     */
    public function show(Category $category, EntityManagerInterface $em)
    {
        return $this->render('backoffice/sites/tag.html.twig', [
            'category' => $category,
            'categories' => $em->getRepository(Category::class)->findAll(),
        ]);
    }

    /**
     * @Route("/{id}/latest", name="sites_tag_show_latest", methods={"GET"}, requirements={"id":"\d+"})
     */
    public function show_latest(Category $category, EntityManagerInterface $em)
    {
        return $this->render('backoffice/sites/tag2.html.twig', [
            'category' => $category,
            'categories' => $em->getRepository(Category::class)->findAll(),
        ]);
    }
}

templates/backoffice/sites/_delete_form.html.twig
<form method="post" action="{{ path('sites_delete', {'id': site.id}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer cet outil ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ site.id) }}">
    <button class="btn btn-outline-danger ml-1 btn-sm">Supprimer</button>
</form>

templates/backoffice/sites/_form.html.twig
{{ form_start(form, { 'attr' : { 'style': 'font-family: "Antic", sans-serif; font-weight:bold;'}}) }}
{{ form_row(form.title) }}
{{ form_row(form.description) }}

{{ form_row(form.link) }}

{{ form_row(form.category, { 'attr' : { 'class': 'd-flex m-4 p-1 flex-wrap tag'}}) }}

<a href="{{ path( 'category_new' ) }}" class="btn btn-outline-info mb-3">Ajouter un mot clé</a>




{{ form_row(form.illustration) }}
         <div class="col-12">
          <h2>Aperçu des illustrations</h2>
          <div class='gallery row border my-3' id="gallery" style="min-height:150px;"></div>
        </div>
{{ form_errors(form) }}

    <button class="btn btn-outline-success m-2">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/backoffice/sites/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un nouveau site{% endblock %}

{% block body %}
<header class="" >
<nav class="col-12 navbar navbar-expand-lg navbar-light  justify-content-center justify-content-between  align-items-start align-items-md-center  d-flex  flex-md-column .flex-row">
<div class=" title__header d-flex justify-content-center align-items-center header">
  <img class="logo m-3" src="{{asset('assets/images/icon.png')}}" alt="">
 <h1 class="color_1 "  >Petites aides</h1>
</div>

 <p class="font-italic color_1 m-4 d-none d-md-block">
Une collection d'outils en ligne à usage unique gratuits pour les développeurs Web...</p>
 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse col-12 my-4" id="navbarTogglerDemo02">
    <ul class="navbar-nav  d-flex justify-content-center align-items-start flex-column">
      <li class="">
        <h2 >Catégories </h2>
      </li>
      <li class="nav-item d-flex m-2">
        <a class="nav-link" href="{{ path('sites_index') }}">Toutes les catégories</a>
      </li>
      {% for categorie in categories %}
 
      {% if categorie.sites|length > 0 %}
      <li class="nav-item d-flex m-2 ">
        <a class="nav-link col-10" href="{{ path('sites_tag_show', {'id': categorie.id}) }}">{{ categorie.title }} </a>

        <p class="nav-link col-2">{{categorie.sites|length}}</p>
</li>
{% endif %}   
     {% endfor %}
    </ul>

  </div>
</nav>

</header>

<section class=" content" >
<section class="reseaux w-100 title__header ">
<div class="col-11 d-flex justify-content-end align-items-center">
 
{% if is_granted('IS_AUTHENTICATED_FULLY') %}
  <i class="las la-user-circle"></i>
  <p class="m-2">{{ app.user.username }}</p>
  <a class="ml-2 m-2  btn btn-outline-dark " href="{{ path('app_logout') }}">Déconnexion</a>
{% endif %}
</div>
</section>

{% if is_granted('IS_AUTHENTICATED_FULLY') %}
<section class="menu__admin w-100 p-4 d-flex justify-content-start align-items-center flex-column flex-md-row">
<p class="px-4">Vous pouvez réaliser les actions suivantes :</p>
<a href="{{ path('index') }}" class="btn btn-outline-danger mx-4 m-1">Retourner au site</a>
<a href="{{ path('sites_new') }}" class="btn btn-outline-danger mx-4 m-1">Ajouter un site/outil</a>
 {% if is_granted('ROLE_ADMIN') %}
<a href="{{ path('category_index') }}" class="btn btn-outline-danger mx-4 m-1">Gérer les catégories</a>
{% endif %}
</section>
{% endif %}

<section class="debut col-12 d-flex flex-column flex-md-row">
  <h3 class="debut__title col-md-6 col-sm-12 p-4 text-md-left text-center">Ajouter un nouveau site/outil</h3>
   <a class=" m-4 btn btn-outline-dark" href="{{ path('sites_index') }}">Retourner à la liste des sites</a>
</section>

<section class="sites col-12 d-flex flex-wrap justify-content-around">

<div class="w-75">
 {{ include('backoffice/sites/_form.html.twig', {'button_label': 'Mise à jour'}) }}

    {{ include('backoffice/sites/_delete_form.html.twig') }}
</div>
    

   
   
    

  
  
  

</section>
</section>

{% endblock %}

templates/backoffice/sites/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil site backoffice{% endblock %}

{% block body %}
<header class="" >
<nav class="col-12 navbar navbar-expand-lg navbar-light  justify-content-center justify-content-between  align-items-start align-items-md-center  d-flex  flex-md-column .flex-row">
<div class=" title__header d-flex justify-content-center align-items-center header">
  <img class="logo m-3" src="{{asset('assets/images/icon.png')}}" alt="">
 <h1 class="color_1 "  >Petites aides</h1>
</div>

 <p class="font-italic color_1 m-4 d-none d-md-block">
Une collection d'outils en ligne à usage unique gratuits pour les développeurs Web...</p>
 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse col-12 my-4" id="navbarTogglerDemo02">
    <ul class="navbar-nav  d-flex justify-content-center align-items-start flex-column">
      <li class="">
        <h2 >Catégories </h2>
      </li>
      <li class="nav-item d-flex m-2">
        <a class="nav-link" href="{{ path('sites_index') }}">Toutes les catégories</a>
      </li>
      {% for categorie in categories %}
 
      {% if categorie.sites|length > 0 %}
      <li class="nav-item d-flex m-2 ">
        <a class="nav-link col-10" href="{{ path('sites_tag_show', {'id': categorie.id}) }}">{{ categorie.title }} </a>

        <p class="nav-link col-2">{{categorie.sites|length}}</p>
</li>
{% endif %}   
     {% endfor %}
    </ul>

  </div>
</nav>

</header>

<section class=" content" >
<section class="reseaux w-100 title__header ">
<div class="col-11 d-flex justify-content-end align-items-center">

{% if is_granted('IS_AUTHENTICATED_FULLY') %}
  <i class="las la-user-circle"></i>
  <p class="m-2">{{ app.user.username }}</p>
  <a class="ml-2 m-2  btn btn-outline-dark " href="{{ path('app_logout') }}">Déconnexion</a>
{% endif %}
</div>
</section>


{% if is_granted('IS_AUTHENTICATED_FULLY') %}
<section class="menu__admin w-100 p-4 d-flex justify-content-start align-items-center flex-column flex-md-row">
<p class="px-4">Vous pouvez réaliser les actions suivantes :</p>
<a href="{{ path('index') }}" class="btn btn-outline-danger mx-4 m-1">Retourner au site</a>
<a href="{{ path('sites_new') }}" class="btn btn-outline-danger mx-4 m-1">Ajouter un site/outil</a>
 {% if is_granted('ROLE_ADMIN') %}
<a href="{{ path('category_index') }}" class="btn btn-outline-danger mx-4 m-1">Gérer les catégories</a>
{% endif %}
</section>
{% endif %}


<section class="debut col-12 d-flex flex-column flex-md-row">
  <h3 class="debut__title col-md-4 col-sm-12 p-4 text-md-left text-center">Tous les outils</h3>
  <div class="col-md-8 col-sm-12 p-4 m-2 sort d-flex justify-content-center justify-content-md-end align-items-center">
  
    <a href="{{ path('sites_index') }}" class="mr-4 normal__link" >Trier par nom</a>
    <a href="{{ path('sites_index_latest') }}" class="mr-4 normal__link"  >Trier par  date</a>
  </div>
</section>

<section class="sites col-12 d-flex flex-wrap justify-content-around">


 {% for site in sites|sort((a, b) => a.title <=> b.title) %}
 
  <div class="site   my-4 ">
    <div class="site__part1">
      <p class="site__date p-1 rounded">Added {{site.publishedAt|date("d/m/Y")}}</p>
      <a class="site__image"  href="{{site.link}}"><img src="{{asset('assets/images/' ~ site.illustration) }}" alt=""></a>
    </div>
    <div class="site__part2">
      <h3 class="site__title p-2">{{ site.title}}</h3>
      <div class="site__category p-2 d-flex ">
            <a class=" btn btn-outline-info btn-sm" href="{{ path('tag_show', {'id': site.category.id}) }}">{{ site.category.title }}</a>
             {% if is_granted('ROLE_ADMIN') %}
         {{ include('backoffice/sites/_delete_form.html.twig') }}
         {% endif %}
          <a href="{{ path('sites_edit', { id: site.id }) }}" class="btn btn-outline-success ml-1 ">Modifier</a>
      </div>

      <p class="site__content p-2 text-justify">{{site.description}}</p>
      <div class="site__link w-100 text-center">
            <a class="normal__link"  href="{{site.link}}"> Go to {{ site.title}}</a>

      </div>
    </div>
    </div>

  
  
  </div>
  {% endfor %}
</section>
</section>

{% endblock %}

templates/backoffice/sites/index2.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil site backoffice{% endblock %}

{% block body %}
<header class="" >
<nav class="col-12 navbar navbar-expand-lg navbar-light  justify-content-center justify-content-between  align-items-start align-items-md-center  d-flex  flex-md-column .flex-row">
<div class=" title__header d-flex justify-content-center align-items-center header">
  <img class="logo m-3" src="{{asset('assets/images/icon.png')}}" alt="">
 <h1 class="color_1 "  >Petites aides</h1>
</div>

 <p class="font-italic color_1 m-4 d-none d-md-block">
Une collection d'outils en ligne à usage unique gratuits pour les développeurs Web...</p>
 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse col-12 my-4" id="navbarTogglerDemo02">
    <ul class="navbar-nav  d-flex justify-content-center align-items-start flex-column">
      <li class="">
        <h2 >Catégories </h2>
      </li>
      <li class="nav-item d-flex m-2">
        <a class="nav-link" href="{{ path('sites_index') }}">Toutes les catégories</a>
      </li>
      {% for categorie in categories %}
 
      {% if categorie.sites|length > 0 %}
      <li class="nav-item d-flex m-2 ">
        <a class="nav-link col-10" href="{{ path('sites_tag_show', {'id': categorie.id}) }}">{{ categorie.title }} </a>

        <p class="nav-link col-2">{{categorie.sites|length}}</p>
</li>
{% endif %}   
     {% endfor %}
    </ul>

  </div>
</nav>

</header>

<section class=" content" >
<section class="reseaux w-100 title__header ">
<div class="col-11 d-flex justify-content-end align-items-center">

{% if is_granted('IS_AUTHENTICATED_FULLY') %}
  <i class="las la-user-circle"></i>
  <p class="m-2">{{ app.user.username }}</p>
  <a class="ml-2 m-2  btn btn-outline-dark " href="{{ path('app_logout') }}">Déconnexion</a>
{% endif %}
</div>
</section>


{% if is_granted('IS_AUTHENTICATED_FULLY') %}
<section class="menu__admin w-100 p-4 d-flex justify-content-start align-items-center flex-column flex-md-row">
<p class="px-4">Vous pouvez réaliser les actions suivantes :</p>
<a href="{{ path('index') }}" class="btn btn-outline-danger mx-4 m-1">Retourner au site</a>
<a href="{{ path('sites_new') }}" class="btn btn-outline-danger mx-4 m-1">Ajouter un outil/site</a>
 {% if is_granted('ROLE_ADMIN') %}
<a href="{{ path('category_index') }}" class="btn btn-outline-danger mx-4 m-1">Gérer les catégories</a>
{% endif %}
</section>
{% endif %}


<section class="debut col-12 d-flex flex-column flex-md-row">
  <h3 class="debut__title col-md-4 col-sm-12 p-4 text-md-left text-center">Tous les outils</h3>
  <div class="col-md-8 col-sm-12 p-4 m-2 sort d-flex justify-content-center justify-content-md-end align-items-center">
  
    <a href="{{ path('sites_index') }}" class="mr-4 normal__link" >Trier par nom</a>
    <a href="{{ path('sites_index_latest') }}" class="mr-4 normal__link"  >Trier par  date</a>
  </div>
</section>

<section class="sites col-12 d-flex flex-wrap justify-content-around">


 {% for site in sites|sort((b, a) => a.publishedAt <=> b.publishedAt) %}
 
  <div class="site   my-4 ">
    <div class="site__part1">
      <p class="site__date p-1 rounded">Added {{site.publishedAt|date("d/m/Y")}}</p>
      <a class="site__image"  href="{{site.link}}"><img src="{{asset('assets/images/' ~ site.illustration) }}" alt=""></a>
    </div>
    <div class="site__part2">
      <h3 class="site__title p-2">{{ site.title}}</h3>
      <div class="site__category p-2 ">
            <a class=" btn btn-outline-info btn-sm" href="{{ path('tag_show', {'id': site.category.id}) }}">{{ site.category.title }}</a>
             {% if is_granted('ROLE_ADMIN') %}
         <a href="{{ path('sites_delete', { id: site.id }) }}" class="btn btn-outline-warning">Effacer</a>
         {% endif %}
          <a href="{{ path('sites_edit', { id: site.id }) }}" class="btn btn-outline-success">Modifier</a>
      </div>

      <p class="site__content p-2 text-justify">{{site.description}}</p>
      <div class="site__link w-100 text-center">
            <a class="normal__link"  href="{{site.link}}"> Go to {{ site.title}}</a>

      </div>
    </div>
    </div>

  
  
  </div>
  {% endfor %}
</section>
</section>

{% endblock %}